
name: Actions WF

on: 
  push:
  pull_request:
    types: [closed, assigned, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkouting
        uses: actions/checkout@v1

      -  name: Lists
         run: 
           echo $GITHUB_SHA
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           #echo "${{github.token}}"
           #git clone git@github:$GITHUB_REPOSITORY
           #git checkout $GITHUB_SHA




